import { LANGUAGE } from './enums';

const translation = {
  'Welcome': {
    [LANGUAGE.UK]: 'Вітаємо',
  },
  "It's": {
    [LANGUAGE.UK]: 'Це',
  },
  'personal finance planner.': {
    [LANGUAGE.UK]: 'персональний планувальник фінансів.',
  },
  'Here will be some description.': {
    [LANGUAGE.UK]: 'Тут буде опис продукту',
  },
  'Settings': {
    [LANGUAGE.UK]: 'Налаштування',
  },
  'Sign Up': {
    [LANGUAGE.UK]: 'Зареєструватсь',
  },
  'Sign In': {
    [LANGUAGE.UK]: 'Увійти',
  },
  'Profile': {
    [LANGUAGE.UK]: 'Профіль',
  },
  'Logout': {
    [LANGUAGE.UK]: 'Вийти',
  },
  'Language': {
    [LANGUAGE.UK]: 'Мова',
  },
  'hours': {
    [LANGUAGE.UK]: 'годин',
  },
  'Cannot get your profile info': {
    [LANGUAGE.UK]: 'Не вдається отримати дані вашого профілю',
  },
  'Username': {
    [LANGUAGE.UK]: "Ім'я користувача",
  },
  'First name': {
    [LANGUAGE.UK]: "Ім'я",
  },
  'Last name': {
    [LANGUAGE.UK]: "Прізвище",
  },
  'Password': {
    [LANGUAGE.UK]: "Пароль",
  },
  'Repeat password': {
    [LANGUAGE.UK]: "Повторіть пароль",
  },
  'Verification code': {
    [LANGUAGE.UK]: "Код підтвердження",
  },
  'Submit': {
    [LANGUAGE.UK]: "Підтвердити",
  },
  'Create new': {
    [LANGUAGE.UK]: "Створити нову",
  },
  'Remove': {
    [LANGUAGE.UK]: "Видалити",
  },
  'Title': {
    [LANGUAGE.UK]: "Заголовок",
  },
  'Description': {
    [LANGUAGE.UK]: "Опис",
  },
  'Users': {
    [LANGUAGE.UK]: "Користувачі",
  },
  'End time should be after start time': {
    [LANGUAGE.UK]: "Час завершення повинен бути після часу початку",
  },
  'Duration': {
    [LANGUAGE.UK]: "Тривалість",
  },
  'Save': {
    [LANGUAGE.UK]: "Зберегти",
  },
  'Multi-factor authentication activated': {
    [LANGUAGE.UK]: "Багатофакторну авторизацію активовано",
  },
  'To start using it': {
    [LANGUAGE.UK]: "Щоб почати її використовувати",
  },
  'multi-factor authentication': {
    [LANGUAGE.UK]: "багатофакторну авторизацію",
  },
  'Download authenticator app for your phone': {
    [LANGUAGE.UK]: "Завантажте додаток для авторизації на ваш телефон",
  },
  'etc': {
    [LANGUAGE.UK]: "тощо",
  },
  'Open the app and scan QR code above': {
    [LANGUAGE.UK]: "Відкрийте додаток і скануйте QR код вгорі",
  },
  'Close this modal': {
    [LANGUAGE.UK]: "Закрийте це модальне вікно",
  },
  'Use autogenerated code from mobile app each time you login into this website': {
    [LANGUAGE.UK]: "Використовуйте автоматично згенерований код з мобільного додатка кожного разу коли ви логуєтесь на цей вебсайт",
  },
  'Confirm the action': {
    [LANGUAGE.UK]: "Підтвердіть дію",
  },
  'Do you really want to disable multi-factor authentication?': {
    [LANGUAGE.UK]: "Ви справді хочете вимкнути багатофакторну авторизацію?",
  },
  'QR code': {
    [LANGUAGE.UK]: "QR код",
  },
  'Enable': {
    [LANGUAGE.UK]: "Активувати",
  },
  'Disable': {
    [LANGUAGE.UK]: "Вимкнути",
  },
  'Close': {
    [LANGUAGE.UK]: "Закрити",
  },
  'Confirm': {
    [LANGUAGE.UK]: "Підтвердити",
  },
  'Cancel': {
    [LANGUAGE.UK]: "Скасувати",
  },
};

const i18n = Object
  .keys(LANGUAGE)
  .reduce((accum, key) => ({
    ...accum,
    [key]: (value) => key === LANGUAGE.EN ? value : (translation[value] ? translation[value][key] : value),
  }), {})

export default i18n;